import Head from "next/head";
import { FC } from "react";

export const Seo: FC = () => {
    return (
        <Head>
            <title>Fashional</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}