export const QR_KEY = {
  GET_ADDRESS: "GET_ADDRESS",
  DETELE_ADDRESS: "DELETE_ADDRESS",
  GET_ADDRESS_BY_ID: "GET_ADDRESS_BY_ID",
  GET_PRODUCT_DETAIL: "GET_PRODUCT_DETAIL",
  GET_PRODUCT_SIZE: "GET_PRODUCT_SIZE"
};